# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import droipy_pb2 as droipy__pb2


class DroiStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.loader = channel.unary_unary(
        '/entry.Droi/loader',
        request_serializer=droipy__pb2.Request.SerializeToString,
        response_deserializer=droipy__pb2.Response.FromString,
        )
    self.hook = channel.unary_unary(
        '/entry.Droi/hook',
        request_serializer=droipy__pb2.Request.SerializeToString,
        response_deserializer=droipy__pb2.Response.FromString,
        )
    self.job = channel.unary_unary(
        '/entry.Droi/job',
        request_serializer=droipy__pb2.Request.SerializeToString,
        response_deserializer=droipy__pb2.Response.FromString,
        )
    self.update = channel.unary_unary(
        '/entry.Droi/update',
        request_serializer=droipy__pb2.Request.SerializeToString,
        response_deserializer=droipy__pb2.Response.FromString,
        )


class DroiServicer(object):

  def loader(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def hook(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def job(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def update(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DroiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'loader': grpc.unary_unary_rpc_method_handler(
          servicer.loader,
          request_deserializer=droipy__pb2.Request.FromString,
          response_serializer=droipy__pb2.Response.SerializeToString,
      ),
      'hook': grpc.unary_unary_rpc_method_handler(
          servicer.hook,
          request_deserializer=droipy__pb2.Request.FromString,
          response_serializer=droipy__pb2.Response.SerializeToString,
      ),
      'job': grpc.unary_unary_rpc_method_handler(
          servicer.job,
          request_deserializer=droipy__pb2.Request.FromString,
          response_serializer=droipy__pb2.Response.SerializeToString,
      ),
      'update': grpc.unary_unary_rpc_method_handler(
          servicer.update,
          request_deserializer=droipy__pb2.Request.FromString,
          response_serializer=droipy__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'entry.Droi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
