# -*- encoding: utf8 -*-
ERROR = lambda x: '1360%.3d' % x
FAILED = lambda x: '1361%.3d' % x

UNKNOW = ERROR(0)

#intput
APPID_FORMAT = ERROR(101)
TEXT_LENGTH = ERROR(102)
TOPIC_LENGTH = ERROR(103)
TOPIC_FORMAT = ERROR(104)
ID_EMPTY = ERROR(105)
KEY_EMPTY = ERROR(106)
NUMBER_NEED = ERROR(107)

#mongo insert
CREATE_FAILED = FAILED(200)
DUPLICATE_KEY = ERROR(201)

#mongo query
QUERY_FAILED = FAILED(210)
SEARCH_FAILED = FAILED(220)

#mongo delete/drop
DELETE_FAILED = FAILED(240)

#mongo update
UPDATE_FAILED = FAILED(230)

#Keyword generator
GRAM_PROCESS = FAILED(400)
SEARCH_GRAM = FAILED(410)

#system
AUTHORIZED_PERMISSION = FAILED(510)
