#!/bin/bash

#python -m pip install virtualenv
#pip install grpcio-tools
#python -m grpc_tools.protoc -I . --python_out=. --grpc_python_out=. droipy.proto
source venv/bin/activate
python -m pip install --upgrade pip
python -m pip install grpcio
